package ColeccionesProg.src.main.java.Otros.APUNTES_COLECCIONES.EXAMEN_COLECCIONES.CORRECCION.modelos;

public enum Casa {
    STARK, LANNISTER, TARGARYEN, BARATHEON, GREYJOY, TYRELL, MARTELL, ARRYN
}

